### ISSUE TITLE
Mod somehow makes all blocks lose the mineable/pickaxe tag

### ISSUE THREAD

**Issue by Tsunamori74** [LarsMans64/InfinityButtons#16]
I have singled out this mod as the source of the issue through testing. Having it installed makes every pickaxe-related block lose their pickaxe tool tag, making them effectively unmineable (they break at hand speed and don't drop anything). I have scanned through the logs and sadly no error or warning regarding Infinity Buttons comes up so I don't have any clues as why the issue may be happening.

**Comment by curryducker** [comment]
we know about this, will be fixed in the next release. I forgot to remove the mud brick button from the 1.18 tags

**Comment by curryducker** [comment]
please use the issue form next time so we can fix the issue a lot easier. (doesn't matter right now as we knew about this one)
