### ISSUE TITLE
[Feature Request]: Alt Button suggestions

### ISSUE THREAD

**Issue by LordRelentless** [LarsMans64/InfinityButtons#23]
### Feature Request

My suggestion would be some themed buttons; perhaps a Fallout 4/3 door button and light switch button that's remote. Possibly a few stand alone console buttons (a button on a pedestal or security console looking stand).

### What version of the mod is this request for?

Both

**Comment by LarsMans64** [comment]
Could you add some images of what the fallout door and console button would look like?

**Comment by LordRelentless** [comment]
Sure console button: https://i.imgur.com/SgyUuLM.jpeg
Door button https://static.wikia.nocookie.net/fallout/images/c/c2/FNV_Vault_Door.png/revision/latest/scale-to-width-down/1000?cb=20110513203219
Light Switch https://static.wikia.nocookie.net/fallout/images/3/39/Lightswitch02.jpg/revision/latest/scale-to-width-down/1000?cb=20150519220838

**Comment by curryducker** [comment]
some cool buttons have been added for next update! we hope to release it asap!
