### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tacogerbil** [LarsMans64/InfinityButtons#24]
### Bug

1. What happened?
Server Crash on attempted startup
infinitybuttons-4.0.0-mc1.19.2
Minecraft 1.19.2 with Fabric Loader 0.14.22

2. What did you expect to happen?
Server Not Crash😁

3. How can we reproduce the bug?
start the server and it crashes.

### What version of the mod are you playing?

Fabric

### What version of Minecraft are you playing?

1.19.2

### Latest version

- [X] I am running the latest version of the mod

### latest.log

[latest.log](https://github.com/TeamDiopside/InfinityButtons/files/12409188/latest.log)
[crash-2023-08-17_06.29.47-server.txt](https://github.com/TeamDiopside/InfinityButtons/files/12409204/crash-2023-08-17_06.29.47-server.txt)

**Comment by curryducker** [comment]
seems like a wall lanterns incompatibilty, we'll look into it (also that crash report is 5 days old lol)

**Comment by tacogerbil** [comment]
DOH!!   Sorry!   It didn't didn't generate a crash log..  I just grabbed the latest one assuming it was the latest My apologies :)

**Comment by curryducker** [comment]
fixed in 7fd70b1
