### ISSUE TITLE
[Bug]: Crash when rapidly spamming/breaking emergency button

### ISSUE THREAD

**Issue by Treeways** [LarsMans64/InfinityButtons#27]
### Bug

This bug happens when spamming an Emergency Button with the Extreme Sound Muffler mod on. I tested this in singleplayer in my modpack. In some instances, a sound packet will be sent with a null reference and kick me from the game, despite this being a singleplayer server... In other instances, there was a full game crash. Yet, this doesn't seem to happen with the secret buttons for some reason.

This was also tested on a clean instance. I could not reproduce it with just those two mods there, so it must be some other mod mixin incompatibility...

1. Get an Emergency Button of any color
2. Rapidly place, press and break the button. It may take 4 times, or 30 times. It's weird.
3. Server crash OR player kick

I'm running Quilt `0.20.2` with InfinityButtons `4.0.1-fabric-1.20.1`.

Since this is difficult to reproduce, and I'm running a dev instance, if you're able to look at the log and get a good idea of where this could be happening, I would appreciate it! If not, then I will simply disable the emergency button crafting recipes in my modpack.

### What version of the mod are you playing?

Fabric

### What version of Minecraft are you playing?

1.20.1

### Latest version

- [x] I am running the latest version of the mod

### latest.log

https://mclo.gs/jpcVydE

**Comment by LarsMans64** [comment]
I am confident that this is not an issue regarding Infinity Buttons, but just a bug from Extreme Sound Muffler. There is nothing in the crash report that would suggest Infinity Buttons has anything to do with it. We can't do anything about this, sorry. Infinity Buttons uses the vanilla way of playing sounds, so it must be an issue in Extreme Sound Muffler. You could try to play a lot of sounds at the same time using command blocks if you want to test this further.

**Comment by Treeways** [comment]
No problem. Thanks for your input :)
