### ISSUE TITLE
[Bug]: It doesn´t let me enter to a server 

### ISSUE THREAD

**Issue by JuanPacoPedrodelaMar** [LarsMans64/InfinityButtons#29]
### Bug

1. What happened?
When I tried to join it freezes the game and it never loads
2. What did you expect to happen?
Just load normally
3. How can we reproduce the bug?
It happenned with the latest version of the mod (4.0.1), Fabric loader, Minecraft 1.20.1.

### What version of the mod are you playing?

Fabric

### What version of Minecraft are you playing?

1.20.1

### Latest version

- [X] I am running the latest version of the mod

**Comment by curryducker** [comment]
without any logs we can't do anything

**Comment by JuanPacoPedrodelaMar** [comment]
you mean the logs that are on the game's console while this happen?

**Comment by curryducker** [comment]
there should be a latest.log in the logs folder

**Comment by JuanPacoPedrodelaMar** [comment]
Ok, here you have it.
[latest.log](https://github.com/TeamDiopside/InfinityButtons/files/12704324/latest.log)

**Comment by curryducker** [comment]
there's nothing Infinity Buttons related in that log, it looks like the JEI plugin from polymer core is spamming which probably freezes your game. Try removing Universal Graves

**Comment by JuanPacoPedrodelaMar** [comment]
It was the same, here you have the log if you want to check:
[latest.log](https://github.com/TeamDiopside/InfinityButtons/files/12704452/latest.log)
In fact, I am able to join to the server with all these mods, except when I have infinity buttons installed, so maybe an incompatibility is avoiding it to work properly. Anyways, thank you for trying to help me :)

**Comment by curryducker** [comment]
What kind of minehut server are you trying to join?

**Comment by JuanPacoPedrodelaMar** [comment]
The normal one, I mean, the lobby, the one that you join with "minehut.com"

**Comment by curryducker** [comment]
But infinity buttons isn't a client side mod, it needs to be installed on a server

**Comment by JuanPacoPedrodelaMar** [comment]
So if I have the mod, it should not let me join to vanilla servers? I did not known that

**Comment by curryducker** [comment]
Well, now you know :)
