### ISSUE TITLE
[Bug]: Unable to load model: 'nethersdelight:block/hoglin_mount' model

### ISSUE THREAD

**Issue by Le6barbare** [LarsMans64/InfinityButtons#30]
### Bug

1. What happened?
Hoglin Mount button show black and pink missing texture block on "pressed=false" status

2. Why did it happen?
MC can't load original nethersdelight:hoglin_mount model because it has been renamed "hoglin_trophy.json" in recent Forge version of Nether's Delight

3. How can we reproduce the bug?
    Using:
        - Infinity Buttons [FORGE] 4.0.1 - 1.20.1
        - nethersdelight-1.20.1-4.0.jar (Forge)

Sidenote: Fabric version of Nether's Delight Hoglin Mount model remains named "hoglin_mount.json"

### What version of the mod are you playing?

Forge

### What version of Minecraft are you playing?

1.20.1

### Latest version

- [X] I am running the latest version of the mod

### latest.log

> [Worker-ResourceReload-4/WARN]: Unable to load model: 'nethersdelight:block/hoglin_mount' referenced from: infinitybuttons:hoglin_mount_button#facing=north,pressed=true: java.io.FileNotFoundException: nethersdelight:models/block/hoglin_mount.json

**Comment by curryducker** [comment]
Thanks for pointing out! Will fix it when i have time (probably tomorrow). In the meantime you could make a resource pack that changes the blockstate to point to the correct model to fix the issue :)

**Comment by curryducker** [comment]
I totally forgot about this, im sorry. it has been fixed now
