### ISSUE TITLE
[Bug]: Upgrade Aquatic added buttons lack added recipe and texture

### ISSUE THREAD

**Issue by rafaelkai** [LarsMans64/InfinityButtons#38]
### Bug

1. What happened?
Some of the Upgrade Aquatic added stone bricks buttons lack a recipe and textures.
2. What did you expect to happen?
Being able to craft them and see their texture.
3. How can we reproduce the bug?
Load Infinity Buttons and Upgrade Aquatic together.

### What version of the mod are you playing?

Forge

### What version of Minecraft are you playing?

1.20.1

### Latest version

- [X] I am running the latest version of the mod

**Comment by curryducker** [comment]
ah i see, they removed kelp variants, i will release a fix as soon as possible

**Comment by curryducker** [comment]
i will remove the blocks though, as they don't exist anymore in the original mod. Crafting them will not be possible.

**Comment by curryducker** [comment]
fix has been released, should be up in a few minutes as curseforge has to review it first

**Comment by rafaelkai** [comment]
Thanks for the quick fix!
