### ISSUE TITLE
[Bug]: "Fancy" Emergency Buttons Block Drops

### ISSUE THREAD

**Issue by fzzyhmstrs** [LarsMans64/InfinityButtons#41]
### Bug

Fancy Emergency Button and Fancy Safe Emergency Button don't have any block drops. 

### What version of the mod are you playing?

Fabric

### What version of Minecraft are you playing?

1.20.1

### Latest version

- [X] I am running the latest version of the mod

### latest.log

I'm running 4.0.1. Opened the latest jar off CF and see the files missing still. No Crash. If you go look in your `/generated/data/` folder (or the data folder of the .jar as mentioned) you'll see the files missing.

![image](https://github.com/TeamDiopside/InfinityButtons/assets/72876796/da8e10df-cffa-4158-8689-ec7840e49c08)

![image](https://github.com/TeamDiopside/InfinityButtons/assets/72876796/8e0fdf39-8989-4560-8c2e-861e16428017)

**Comment by curryducker** [comment]
Well that's awkward. I'm wondering why nobody reported this already. Will be fixed in a bit

**Comment by curryducker** [comment]
Should be fixed, thanks for reporting!
